# 1.Array ใช้จัดการ metrix

In [1]:
L=[[1,2,3],[4,5,6]]#list

In [2]:
import numpy as np

In [7]:
a=np.array(L) #change to array metrix
type(a)

numpy.ndarray

In [4]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
a.shape #dimension

(2, 3)

In [9]:
a[0]

array([1, 2, 3])

In [10]:
a[0,0]

1

In [11]:
x=np.arange(0,3) #make range is goint to array

In [12]:
type(x)

numpy.ndarray

In [13]:
a=np.arange(60).reshape(2,5,6)

In [16]:
a.shape

(2, 5, 6)

In [17]:
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]]])

# 2.object oreinted programing

In [18]:
a=1

In [19]:
a.bit_length() #method use to had ()

1

In [20]:
a.real #properties not use to had ()

1

In [26]:
T=()
dir(T) #all method for T

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [27]:
L=[]

In [29]:
set(dir(T)) & set(dir(L))#To intersect dir method

{'__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index'}

# 3.กระบวนวิธีพื้นฐาน

In [30]:
import numpy as np

In [31]:
a= np.arange(60)

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [33]:
a.argmax()#max value

59

In [34]:
a.argmin()#min value

0

In [35]:
a.mean()

29.5

In [37]:
a.cumsum()

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485,
       1540, 1596, 1653, 1711, 1770], dtype=int32)

In [39]:
help(a.cumsum)#description

Help on built-in function cumsum:

cumsum(...) method of numpy.ndarray instance
    a.cumsum(axis=None, dtype=None, out=None)
    
    Return the cumulative sum of the elements along the given axis.
    
    Refer to `numpy.cumsum` for full documentation.
    
    See Also
    --------
    numpy.cumsum : equivalent function



In [40]:
a.reshape(2,6,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [41]:
a.shape

(60,)

In [42]:
a.resize(2,6,5)

In [43]:
a.shape

(2, 6, 5)

In [44]:
a.transpose()

array([[[ 0, 30],
        [ 5, 35],
        [10, 40],
        [15, 45],
        [20, 50],
        [25, 55]],

       [[ 1, 31],
        [ 6, 36],
        [11, 41],
        [16, 46],
        [21, 51],
        [26, 56]],

       [[ 2, 32],
        [ 7, 37],
        [12, 42],
        [17, 47],
        [22, 52],
        [27, 57]],

       [[ 3, 33],
        [ 8, 38],
        [13, 43],
        [18, 48],
        [23, 53],
        [28, 58]],

       [[ 4, 34],
        [ 9, 39],
        [14, 44],
        [19, 49],
        [24, 54],
        [29, 59]]])

In [45]:
b=a.flatten()#go to 1 dimension

In [46]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [47]:
b.shape

(60,)

In [48]:
b.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [49]:
b.resize(10,6)

In [50]:
b.T

array([[ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55],
       [ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56],
       [ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57],
       [ 4, 10, 16, 22, 28, 34, 40, 46, 52, 58],
       [ 5, 11, 17, 23, 29, 35, 41, 47, 53, 59]])

# 5. การคำนวณทางพิชคณิต

In [53]:
a=[[1,2],[3,4]]
A=np.array(a)
b=[[1,-2],[-3,4]]
B=np.array(b)

In [57]:
A*B #การคูณแบบทั่งไปตามตำแหน่ง

array([[ 1, -4],
       [-9, 16]])

In [56]:
np.dot(A,B) #การคูณเมตริกซ์

array([[-5,  6],
       [-9, 10]])

In [58]:
import numpy.linalg as lin

In [61]:
Ainv= lin.inv(A) #การหา invers

In [60]:
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [62]:
np.dot(A,Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [63]:
np.dot(Ainv,A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [66]:
np.linalg.tensorinv(A,ind= 1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### โจทย์    
2x-y+2z=6,<br> 
x-y+3z=8, <br> 
4x+5z=5, <br> 

In [67]:
A=np.array([[2,-1,2],[1,-1,3],[4,0,5]])

In [73]:
b=np.array([6,8,5])

In [74]:
Ainv=lin.inv(A)

In [78]:
r=np.dot(Ainv,b)
r

array([-0.55555556, -4.22222222,  1.44444444])

In [76]:
A[0]

array([ 2, -1,  2])

In [79]:
np.dot(A[0],r)

6.0

In [80]:
np.dot(A[1],r)

8.0

In [81]:
np.dot(A[2],r)

5.0

## Eigant value and Eigant vector

In [82]:
A=np.array([[1,2,3],[4,5,2],[7,6,5]])

In [83]:
np.linalg.eigvals(A)

array([11.28041742, -1.83030721,  1.54988979])

In [84]:
np.linalg.eig(A)

(array([11.28041742, -1.83030721,  1.54988979]),
 array([[ 0.33031999,  0.78568336,  0.3607414 ],
        [ 0.47088026, -0.3020298 , -0.7441554 ],
        [ 0.8180223 , -0.53988856,  0.56222627]]))

In [85]:
values ,vecs =np.linalg.eig(A)

In [86]:
values

array([11.28041742, -1.83030721,  1.54988979])

In [87]:
vecs

array([[ 0.33031999,  0.78568336,  0.3607414 ],
       [ 0.47088026, -0.3020298 , -0.7441554 ],
       [ 0.8180223 , -0.53988856,  0.56222627]])